### Will be empty at first

GET http://localhost:5000/api/Greetings HTTP/1.1


### Now add a Greetings

POST http://localhost:5000/api/Greetings HTTP/1.1
Content-Type: application/json

{
    "Message" : "Hello World"
}

### Now see that greeting

GET http://localhost:5000/api/Greetings/{xxxx-xxxx-xxxx-xxx} HTTP/1.1


### Now add some more greetings

POST http://localhost:5000/api/Greetings HTTP/1.1
Content-Type: application/json

{
    "Message" : "Hello Mary"
}

### And even more

POST http://localhost:5000/api/Greetings HTTP/1.1
Content-Type: application/json

{
    "Message" : "Hello Alice"
}


### Now see all the greeetings

GET http://localhost:5000/api/Greetings HTTP/1.1
